name = "KinbiontPlots"
uuid = "6174cffe-3aeb-40a0-b6ea-f169f792c023"
authors = ["Fabrizio Angaroni", "Edgar Zanella Alvarenga"]
version = "1.0.0"

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
Kinbiont = "3b7c519f-be5e-4159-a208-6486ce96bb37"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"

[compat]
julia = "1.10"
CSV ="0.10.14"
Kinbiont = "1.40.0"

